In [257]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

数据处理
--

1 得到原始数据和离散，连续列

In [258]:
data_path='/media/xuweijia/DATA/代码/python_test/data/Criteo/demo_data/'
file_name='train.csv'

In [259]:
# get raw data
raw_df=pd.read_csv(os.path.join(data_path+file_name))
raw_df=raw_df.drop(["Id"],axis=1)
raw_df

Label   I1   I2    I3    I4      I5     I6     I7    I8     I9  ...  \
0         1  1.0    0   1.0   NaN   227.0    1.0  173.0  18.0   50.0  ...   
1         1  4.0    1   1.0   2.0    27.0    2.0    4.0   2.0    2.0  ...   
2         1  0.0  806   NaN   NaN  1752.0  142.0    2.0   0.0   50.0  ...   
3         0  2.0   -1  42.0  14.0   302.0   38.0   25.0  38.0   90.0  ...   
4         1  0.0   57   2.0   1.0  2891.0    2.0   35.0   1.0  137.0  ...   
...     ...  ...  ...   ...   ...     ...    ...    ...   ...    ...  ...   
1594      0  NaN    8   1.0   1.0    43.0    NaN    0.0   1.0    1.0  ...   
1595      0  8.0    2  20.0   8.0    36.0    9.0    8.0  10.0    8.0  ...   
1596      0  0.0    1   2.0  12.0  4877.0  140.0   13.0  34.0  136.0  ...   
1597      0  NaN    2   NaN   1.0  1972.0    NaN    0.0   1.0   14.0  ...   
1598      1  NaN   34   3.0   4.0     NaN    NaN    0.0   4.0   14.0  ...   

           C17       C18       C19       C20       C21       C22       C23  \
0     3486227d  e88ffc9d  c393dc22  b1252a9d  57c90cd9       NaN  bcdee96c   
1     07c540c4  92555263       NaN       NaN  242bb710       NaN  3a171ecb   
2     07c540c4  25c88e42  21ddcdc9  b1252a9d  a0136dd2       NaN  32c7478e   
3     e5ba7672  5aed7436  21ddcdc9  b1252a9d  c3abeb21       NaN  423fab69   
4     e5ba7672  642f2610  1d1eb838  b1252a9d  1640d50b  ad3062eb  423fab69   
...        ...       ...       ...       ...       ...       ...       ...   
1594  1e88c74f  fc35e8fe       NaN       NaN  a02708ad  c9d4222a  c3dc6cef   
1595  e5ba7672  5aed7436  21ddcdc9  b1252a9d  eea796be       NaN  3a171ecb   
1596  e5ba7672  2b0a9d11       NaN       NaN  7453e535       NaN  dbb486d7   
1597  e5ba7672  817481a8       NaN       NaN  e4244d7f  c9d4222a  c7dc6720   
1598  2005abd1  1cdbd1c5       NaN       NaN  288eaded  c9d4222a  bcdee96c   

           C24       C25       C26  
0     4d19a3eb  cb079c2d  456c12a0  
1     72c78f11       NaN       NaN  
2     8fc66e78  001f3601  f37f3967  
3     1793a828  e8b83407  5cef228f  
4     45ab94c8  2bf691b1  c84c4aec  
...        ...       ...       ...  
1594  502f2493       NaN       NaN  
1595  1793a828  e8b83407  5cef228f  
1596  906e72ec       NaN       NaN  
1597  60efe6e6       NaN       NaN  
1598  8fc66e78       NaN       NaN  

[1599 rows x 40 columns]

In [260]:
# 分别找出连续列/离散列
def col_type(df):
    dis_col=[]
    con_col=[]
    columns=df.columns.tolist()
    for c in columns:
        if df[c].dtype=='int64' or df[c].dtype=='float':
            con_col.append(c)
        else:
            dis_col.append(c)
    return dis_col,con_col
dis_col,con_col=col_type(raw_df)
con_col.remove("Label")
target="Label"

2 填充缺失值：数值型填0； 类别填空字符串，到时候也编码进去 （测试数据的缺失值用同样字符填充。相同编码）

In [261]:
null_token = '<NULL>'
raw_df[dis_col]=raw_df[dis_col].fillna(null_token)
raw_df[con_col]=raw_df[con_col].fillna(0)
raw_df

Label   I1   I2    I3    I4      I5     I6     I7    I8     I9  ...  \
0         1  1.0    0   1.0   0.0   227.0    1.0  173.0  18.0   50.0  ...   
1         1  4.0    1   1.0   2.0    27.0    2.0    4.0   2.0    2.0  ...   
2         1  0.0  806   0.0   0.0  1752.0  142.0    2.0   0.0   50.0  ...   
3         0  2.0   -1  42.0  14.0   302.0   38.0   25.0  38.0   90.0  ...   
4         1  0.0   57   2.0   1.0  2891.0    2.0   35.0   1.0  137.0  ...   
...     ...  ...  ...   ...   ...     ...    ...    ...   ...    ...  ...   
1594      0  0.0    8   1.0   1.0    43.0    0.0    0.0   1.0    1.0  ...   
1595      0  8.0    2  20.0   8.0    36.0    9.0    8.0  10.0    8.0  ...   
1596      0  0.0    1   2.0  12.0  4877.0  140.0   13.0  34.0  136.0  ...   
1597      0  0.0    2   0.0   1.0  1972.0    0.0    0.0   1.0   14.0  ...   
1598      1  0.0   34   3.0   4.0     0.0    0.0    0.0   4.0   14.0  ...   

           C17       C18       C19       C20       C21       C22       C23  \
0     3486227d  e88ffc9d  c393dc22  b1252a9d  57c90cd9    <NULL>  bcdee96c   
1     07c540c4  92555263    <NULL>    <NULL>  242bb710    <NULL>  3a171ecb   
2     07c540c4  25c88e42  21ddcdc9  b1252a9d  a0136dd2    <NULL>  32c7478e   
3     e5ba7672  5aed7436  21ddcdc9  b1252a9d  c3abeb21    <NULL>  423fab69   
4     e5ba7672  642f2610  1d1eb838  b1252a9d  1640d50b  ad3062eb  423fab69   
...        ...       ...       ...       ...       ...       ...       ...   
1594  1e88c74f  fc35e8fe    <NULL>    <NULL>  a02708ad  c9d4222a  c3dc6cef   
1595  e5ba7672  5aed7436  21ddcdc9  b1252a9d  eea796be    <NULL>  3a171ecb   
1596  e5ba7672  2b0a9d11    <NULL>    <NULL>  7453e535    <NULL>  dbb486d7   
1597  e5ba7672  817481a8    <NULL>    <NULL>  e4244d7f  c9d4222a  c7dc6720   
1598  2005abd1  1cdbd1c5    <NULL>    <NULL>  288eaded  c9d4222a  bcdee96c   

           C24       C25       C26  
0     4d19a3eb  cb079c2d  456c12a0  
1     72c78f11    <NULL>    <NULL>  
2     8fc66e78  001f3601  f37f3967  
3     1793a828  e8b83407  5cef228f  
4     45ab94c8  2bf691b1  c84c4aec  
...        ...       ...       ...  
1594  502f2493    <NULL>    <NULL>  
1595  1793a828  e8b83407  5cef228f  
1596  906e72ec    <NULL>    <NULL>  
1597  60efe6e6    <NULL>    <NULL>  
1598  8fc66e78    <NULL>    <NULL>  

[1599 rows x 40 columns]

3 可以做一些特征处理上的优化。比如数值型归一化。离散特征出现次数小于某阈值的，值都编码成\<UNK\>。这里忽略，假设已经做过了.也做过了特征选择

4 离散特征label-encode. 保存原始值到label的映射。之后根据映射后的id找对应embedding （取值10个以内的one-hot,作为新特征）
  如果想同一列加工出不同特征。可以用FeatureUnion和自定义transformer来选择列。 （如对文本列同时加工长度和tfidf两个特征）
  ColumnTransformer对同一列只能做一个操作。如果不对同一列做不同操作，就用这个就可以。

In [9]:
# %load FM_helper/LabelEncoder.py

In [262]:
# 直接当做包，引用py中函数
# labelencoding。
from FM_helper import LabelEncoder
reload(LabelEncoder)
trans,new_con_col,new_dis_col,df,raw_df2,cate_counts,cate_feature_map=LabelEncoder.labelencode_trans(raw_df,dis_col,con_col,target)
# 测试.只需要保存大transformer和最终的dis_col,con_col。 用来做转化，以及识别转换后的两类特征。 
LabelEncoder.test(raw_df,trans,new_con_col,new_dis_col,target)

C1     C2      C3     C4    C5   C6     C7    C8   C9    C10  ...  \
0     33.0   27.0   486.0  572.0   1.0  1.0  459.0   1.0  1.0  465.0  ...   
1      0.0   98.0   170.0  287.0   1.0  3.0  550.0  21.0  1.0  683.0  ...   
2      0.0   28.0   114.0  696.0  11.0  3.0  704.0   1.0  1.0  133.0  ...   
3      0.0   12.0   650.0  243.0   1.0  3.0  329.0   1.0  1.0   27.0  ...   
4      0.0   36.0   517.0   70.0   1.0  3.0   20.0   2.0  1.0  166.0  ...   
...    ...    ...     ...    ...   ...  ...    ...   ...  ...    ...  ...   
1594   0.0   93.0   617.0  801.0   1.0  1.0   25.0  12.0  1.0   28.0  ...   
1595  30.0   12.0  1034.0  243.0   1.0  6.0  935.0   1.0  1.0  454.0  ...   
1596  30.0  113.0   676.0    7.0   1.0  6.0  185.0  14.0  1.0  485.0  ...   
1597   0.0   48.0   565.0  727.0   1.0  6.0  377.0   0.0  1.0  202.0  ...   
1598   0.0  155.0   286.0  768.0   1.0  6.0  590.0   1.0  0.0  166.0  ...   

          I5     I6     I7    I8     I9  I10   I11  I12   I13  Label  
0      227.0    1.0  173.0  18.0   50.0  1.0   7.0  1.0   0.0    1.0  
1       27.0    2.0    4.0   2.0    2.0  1.0   1.0  0.0   2.0    1.0  
2     1752.0  142.0    2.0   0.0   50.0  0.0   1.0  0.0   0.0    1.0  
3      302.0   38.0   25.0  38.0   90.0  1.0   3.0  0.0  38.0    0.0  
4     2891.0    2.0   35.0   1.0  137.0  0.0  17.0  0.0   1.0    1.0  
...      ...    ...    ...   ...    ...  ...   ...  ...   ...    ...  
1594    43.0    0.0    0.0   1.0    1.0  0.0   0.0  0.0   1.0    0.0  
1595    36.0    9.0    8.0  10.0    8.0  1.0   1.0  0.0   8.0    0.0  
1596  4877.0  140.0   13.0  34.0  136.0  0.0   2.0  0.0  12.0    0.0  
1597  1972.0    0.0    0.0   1.0   14.0  0.0   0.0  0.0   1.0    0.0  
1598     0.0    0.0    0.0   4.0   14.0  0.0   0.0  0.0   4.0    1.0  

[1599 rows x 40 columns]

标准FM
--

公式：

$$y= b+ \sum_{i}w_ix_i  + \sum_{i}^{n}\sum_{j!=i}^{n}x_ix_j<\vec{v_i},\vec{v_j}>$$

一阶同LR. 每个连续特征对应一个$w_i$,每个离散特征one-hot之后的特征作为新特征，对应一个$w_i$

二阶交互，每个连续特征对应一个embedding。每个离散特征的每个每个特征的每个取值对应一个embedding

因此每个连续特征$x_i$,对应一个$w_i$,一个embedding，用来和其他特征交互。
   每个离散特征域，对应one-hot之后的C个特征$x_i$，对应C个$w_i$,C个embedding

但对每个样本来说，该离散特征one-hot之后，只会根据取值取到一个embedding，一个$w_i$<br/>(该离散特征对一阶的贡献，只有根据样本该离散特征取值映射到的$w_i$，对应取值$x_i$是1,其他C-1位置由于one-hot,该样本下取值$x_i$都是0,贡献是0)

因此总共需要维护（所有连续特征+所有离散特征的所有取值)个特征

假设所有连续特征和one-hot后的所有离散特征共F个,总共需要维护F个特征。可以根据特征名称，把每个特征映射到一个固定id上（位置）:<br/>
每个连续特征对应一个id                            <br/>
每个离散特征的每个取值对应一个id                    <br/>
每个id都维护一个$w_i$,一个embedding，对应该特征在W（F,1）,embedding(F,d)中的位置。<br/>
之后每个样本，都可以根据特征位置去找对应的$w_i$,embedding：       <br/>

因此在对每个样本进行映射时，需要分别得到样本每个特征的位置（id）和取值$x_i$：

位置映射：样本的所有特征都被映射到对应位置,用来找对应的$w_i$,embedding。每个连续特征对应的就是位置id。每个离散域，根据样本在该域的取值映射到对应id。n个离散域，对应n个embedding,n个$w_i$

样本取值：连续特征的取值不变（或者归一化），离散特征取值1，作为样本的$x_i$输入。n个离散域，对应的n个取值，$x_i$都是1。在one-hot后的对应位置上

### 对原始特征进行映射。得到one-hot之后的所有特征（含连续特征）到位置id的映射

In [263]:
from FM_helper import Fmdata
reload(Fmdata)
f_trans=Fmdata.FeaturePosTrans(dis_col,con_col,10)
f_trans.fit(raw_df)
feature_pos,feature_values=f_trans.transform(raw_df)

In [264]:
len(f_trans.feature_id_map)  # 离散特征one-hot后，总的特征数目. NAN+con_col+all_dis

319

In [265]:
f_trans.feature_id_map

{'<NULL>': 0,
 'I1': 1,
 'I2': 2,
 'I3': 3,
 'I4': 4,
 'I5': 5,
 'I6': 6,
 'I7': 7,
 'I8': 8,
 'I9': 9,
 'I10': 10,
 'I11': 11,
 'I12': 12,
 'I13': 13,
 'C1_05db9164': 15,
 'C1_68fd1e64': 16,
 'C1_5a9ed9b0': 17,
 'C1_8cf07265': 18,
 'C1_be589b51': 19,
 'C1_5bfa8ab5': 20,
 'C1_f473b8dc': 21,
 'C1_87552397': 22,
 'C1_ae82ea21': 23,
 'C1_39af2607': 24,
 'C1_9a89b36c': 25,
 'C1_<UNK>': 14,
 'C2_38a947a1': 27,
 'C2_09e68b86': 28,
 'C2_80e26c9b': 29,
 'C2_d833535f': 30,
 'C2_4f25e98b': 31,
 'C2_287130e0': 32,
 'C2_0a519c5c': 33,
 'C2_08d6d899': 34,
 'C2_4c2bc594': 35,
 'C2_38d50e09': 36,
 'C2_207b2d81': 37,
 'C2_58e67aaf': 38,
 'C2_2c16a946': 39,
 'C2_942f9a8d': 40,
 'C2_8947f767': 41,
 'C2_421b43cd': 42,
 'C2_0468d672': 43,
 'C2_8084ee93': 44,
 'C2_78ccd99e': 45,
 'C2_1cfdf714': 46,
 'C2_68b3edbf': 47,
 'C2_e112a9de': 48,
 'C2_95e2d337': 49,
 'C2_e5fb1af3': 50,
 'C2_39dfaa0d': 51,
 'C2_e77e5e6e': 52,
 'C2_9819deea': 53,
 'C2_8cc9c66e': 54,
 'C2_f0cf0024': 55,
 'C2_3df44d94': 56,
 'C2_ae46a2

In [266]:
feature_pos

Label  I1  I2  I3  I4  I5  I6  I7  I8  I9  ...  C17  C18  C19  C20  C21  \
0         1   1   2   3   4   5   6   7   8   9  ...  213  240  249  257  258   
1         1   1   2   3   4   5   6   7   8   9  ...  212  219    0    0  258   
2         1   1   2   3   4   5   6   7   8   9  ...  212  219  250  257  258   
3         0   1   2   3   4   5   6   7   8   9  ...  210  220  250  257  258   
4         1   1   2   3   4   5   6   7   8   9  ...  210  219  249  257  258   
...     ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...   
1594      0   1   2   3   4   5   6   7   8   9  ...  215  219    0    0  258   
1595      0   1   2   3   4   5   6   7   8   9  ...  210  220  250  257  258   
1596      0   1   2   3   4   5   6   7   8   9  ...  210  219    0    0  258   
1597      0   1   2   3   4   5   6   7   8   9  ...  210  219    0    0  258   
1598      1   1   2   3   4   5   6   7   8   9  ...  216  219    0    0  258   

      C22  C23  C24  C25  C26  
0       0  279  284  305  309  
1       0  276  284    0    0  
2       0  275  284  299  309  
3       0  277  287  298  309  
4     270  277  290  301  311  
...   ...  ...  ...  ...  ...  
1594  271  274  284    0    0  
1595    0  276  287  298  309  
1596    0  282  284    0    0  
1597  271  280  284    0    0  
1598  271  279  284    0    0  

[1599 rows x 40 columns]

In [267]:
feature_values

Label   I1   I2    I3    I4      I5     I6     I7    I8     I9  ...  \
0         1  1.0    0   1.0   0.0   227.0    1.0  173.0  18.0   50.0  ...   
1         1  4.0    1   1.0   2.0    27.0    2.0    4.0   2.0    2.0  ...   
2         1  0.0  806   0.0   0.0  1752.0  142.0    2.0   0.0   50.0  ...   
3         0  2.0   -1  42.0  14.0   302.0   38.0   25.0  38.0   90.0  ...   
4         1  0.0   57   2.0   1.0  2891.0    2.0   35.0   1.0  137.0  ...   
...     ...  ...  ...   ...   ...     ...    ...    ...   ...    ...  ...   
1594      0  0.0    8   1.0   1.0    43.0    0.0    0.0   1.0    1.0  ...   
1595      0  8.0    2  20.0   8.0    36.0    9.0    8.0  10.0    8.0  ...   
1596      0  0.0    1   2.0  12.0  4877.0  140.0   13.0  34.0  136.0  ...   
1597      0  0.0    2   0.0   1.0  1972.0    0.0    0.0   1.0   14.0  ...   
1598      1  0.0   34   3.0   4.0     0.0    0.0    0.0   4.0   14.0  ...   

      C17  C18  C19  C20  C21  C22  C23  C24  C25  C26  
0     1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  
1     1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  
2     1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  
3     1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  
4     1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  
1594  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  
1595  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  
1596  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  
1597  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  
1598  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  

[1599 rows x 40 columns]

### 建立自己的dataset和对应的dataloader

In [268]:
# 建dataset: 都放np,防止loader开多进程内存泄露:https://github.com/pytorch/pytorch/issues/13246#issuecomment-893198671）
class Mydata(Dataset):
    def __init__(self,fv,fp,target,mode='train'):
        super(Mydata, self).__init__()
        self.fv=fv           # np: m,n.  每个样本的特征取值 
        self.fp=fp           #           每个样本的特征位置.如果太大以后可以放np文件名.或切成多个文件,每次只打开一个(类似drml)
        self.target=target   #           如果mode==train/valid.对应y. mode==test,没有y，对应id 
    def __len__(self):
        return len(self.fv)
    def __getitem__(self, index):
        return self.fp[index,:],self.fv[index],self.target[index]  # 提前做好了映射。当然映射也可以在这里做。

allcols=dis_col+con_col
trainDataset=Mydata(feature_values[allcols].values,feature_pos[allcols].values, raw_df[target].values)

In [288]:
# DataLoader:   valid同
trainloader = DataLoader(trainDataset,        
                    shuffle=True,             # 每个epoch全部shuffle
                    batch_size=32,
                    collate_fn=None,          # 自定义如何拼batch。默认有，一般不需要。可以用来对batch padding（根据每个batch最长的text）
                                              # 传入的是一个batch，B个tuple. 每个tuple对应Dataset传出来的n个元素。
                                              # 自己重新拼成n个元素，每个元素B行，作为loader每次迭代的返回
                    pin_memory=False,         # 页锁定内存：不可分页，占用物理内存。 可分页内存：占用虚拟内存，用时候从磁盘读入物理内存
                                                # gpu需要通过页锁定内存中，把数据复制到gpu上
                                                #  数据从cpu的可分页内存内存传到gpu时，需要先把数据复制到临时的页锁定内存，再赋值到gpu.速度更慢
                                                #  如果指定pin_memory=True, batch的数据会直接被放在cpu的页锁定内存中，传到gpu时更快。少了一步复制
                                                #  但页锁定内存会占用真实物理内存，分配过多会挤占别的程序的内存，把内存耗尽。因此内存小时不建议用
                    sampler=None,             # 定义/自定义怎么从dataset里抽取每个batch的样本.还有一个batch_sampler参数
                                              # 需要实现__iter__方法。返回针对所有样本id的迭代器，顺序按自定义的样本顺序排好
                                              # 需要实现 __len__ ， 表示loader的一次抽取完成。一般同dataset样本数。
                                              # 就不能定义shuffle了，因为策略自己实现了。shuffle只能在iter里自己做。加入随机性
                                              # 每次loader会根据__iter__(和batch_size），迭代产生该epoch的每个batch。 
                                              # 比如nlp会根据样本文本长度，将长度相近样本排一起：iter([25,3,60,0,...1])。使得每个batch长度接近
                                              # 通过在__iter_里先切好batch,再shuffle,再整合。打乱每个epoch,batch间的执行顺序
                                              # 可以设置RandomSampler每次随机采样。（可参考该实现等）                       
                    num_workers=10            # 开多进程，每个进程计算一个batch。初始化时用之前提前处理好对应的n个batch。后续batch加入新的线程
                   )                          # 初始化时会一次性建好n个进程。每个进程提前处理好要用的batch数据。（底层是 multiprocessing）

In [289]:
epoch_num=3
for epoch in range(epoch_num):
    for batch_id,x in enumerate(trainloader):   # 把数据完整轮询一遍。对应一个epoch
        # 输入模型
        break

In [290]:
x

[tensor([[15, 26, 59,  ..., 11, 12, 13],
         [15, 26, 59,  ..., 11, 12, 13],
         [15, 26, 59,  ..., 11, 12, 13],
         ...,
         [14, 28, 63,  ..., 11, 12, 13],
         [18, 34, 59,  ..., 11, 12, 13],
         [15, 34, 59,  ..., 11, 12, 13]]),
 tensor([[ 1.,  1.,  1.,  ...,  2.,  0.,  0.],
         [ 1.,  1.,  1.,  ...,  1.,  0., 13.],
         [ 1.,  1.,  1.,  ...,  0.,  0.,  1.],
         ...,
         [ 1.,  1.,  1.,  ...,  3.,  0.,  0.],
         [ 1.,  1.,  1.,  ...,  0.,  0., 29.],
         [ 1.,  1.,  1.,  ...,  4., 12.,  4.]], dtype=torch.float64),
 tensor([0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 1, 0, 0, 0, 1])]

In [291]:
f_p,f_v,y=x[0],x[1],x[2]

### 原始FM模型

模型维持n个w,n个embedding，对应one-hot后的所有特征（这里还算上了缺失值对应的0参数）

二阶分数是$$\sum_{i}^{n}\sum_{j!=i}^{n}x_ix_j<\vec{v_i},\vec{v_j}>$$

直接计算是$O(n^2*k)$。每对向量内积是$k$,共$O(n^2)$个pair。最后求和

等价于embedding们对应位置22相乘后，再求和。可以先求所有embedding每个维度元素22相乘的和，最后再对所有维度求和

$$\sum_{i}^{n}\sum_{j!=i}^{n}<\vec{e_i},\vec{e_j}>= \sum_{f} \sum_{i}^{n}\sum_{j!=i}^{n}e_{if}*e_{jf} $$

embedding的每个维度元素22相乘的和： $ab+ac+bc= \frac{1}{2}((a+b+c)^2-(a^2+b^2+c^2))$

因此对固定维度，embedding的每个维度元素22相乘的和$\sum_{i}^{n}\sum_{j!=i}^{n}e_{if}*e_{jf}$ ，是$\frac{1}{2}((e_{if}+e_{jf}...)^2-(e_{if}^2+e_{if}^2+...))$

可以通过每个embedding相加（对应位置相加）的平方，减去每个embedding平方的相加，得到（1，k）的向量，作为embedding的每个维度元素22交互的结果。最终的二阶分数是这k个维度的结果相加。

也可以把这k维向量作为新的隐特征，输入后续网络。作为FM/deepFM的一个小变体

转化后，$\frac{1}{2}((e_{if}+e_{jf}...)^2-(e_{if}^2+e_{if}^2+...))$的复杂度只有$O(n)$(n个元素相加或平方后相加)。加上维度F，总的复杂度可以降低到$O(nk)$

In [447]:
class FM(nn.Module):
    def __init__(self,n_field,n_features,embed_size,dropout=0.2):
        """
        标准FM
        n_field: 原始离散特征数目
        n_features: 离散特征one-hot之后,和dense的总特征个数. 这里包含了一个缺失值特征向量，paddding成0
        """
        super(FM, self).__init__()
        self.n_field=n_field             # 原始特征数目
        self.n_features=n_features       # 连续+离散特征的总数目 (离散特征one-hot+unique化后的。且算上最终的一个padding)
        self.k=embed_size
        
        self.W=nn.Embedding(n_features,1,padding_idx=0)                       # 每个特征对应的wi。位置0是0对梯度无贡献。embedding默认是N(0,1)
        self.w0=nn.Parameter(torch.zeros([1,]))                               # b初始化为0
        self.feature_embed=nn.Embedding(n_features,embed_size,padding_idx=0)  # 每个特征对应的embedding
        self.droplayer=nn.Dropout(dropout)
        
        self.weight=nn.Parameter(0.5*torch.ones([2,]))                        # 一阶，二阶score的权重 
                                                                              
        self.__init_weight__()                                                # 初始化权重(可以不调用，用默认的)
            
    def __init_weight__(self):              # 初始化权重.默认是N(0,1)
        inn=n_features-1
        # 自定义uniform_，参考drml （deepFM用的tf.random_normal）
        init_embed = np.random.uniform(low=-np.sqrt(1 / inn), high=np.sqrt(1 / inn), size=(inn, embed_size)).astype(np.float32)
        self.feature_embed.weight[1:].data.copy_(torch.tensor(init_embed))
        nn.init.normal_(self.W.weight[1:],0, np.sqrt(2.0 /inn))
        # kaiming_normal_
        #nn.init.kaiming_uniform_(self.feature_embed.weight[1:], mode='fan_in', nonlinearity='relu')  # sqrt(6/inn) 
        # normal
        #nn.init.normal_(self.feature_embed.weight[1:],0, np.sqrt(2.0 / (inn + embed_size)))  
        # nn.init.xavier_normal_(self.feature_embed.weight[1:])             # embedding 默认是N(0,1)。
        
    def forward(self,f_p,f_x): # B,n.  n是每个样本的原始特征数目
        """
        f_p: (B,N)  每个样本的原始特征，根据特征名（连续特征）/特征取值（离散特征）被映射到embedding上的位置。 N:原始特征数目
        f_x: (B,N)  每个样本的原始特征，对应的取值。 离散特征对应的是one-hot后的，所以在对应的f_p上取值为1
        """
        batch_size=f_p.shape[0]
        
        # 一阶score
        w=self.W(f_p).reshape(batch_size,-1)              # B,n   每个样本根据原始特征，找到对应位置处的w
        y_score1=self.w0 + torch.sum(torch.mul(w,f_x),1)  # B,1   wixi+b  B,n -->   B,1.  要是不sum，也可以作为n个特征。之后作为deepFM的改造
        
        # 二阶score
        embed=self.feature_embed(f_p)                     # B,n,d 每个样本根据原始特征，找到对应位置处的embedding
        
        embed=torch.mul(embed,f_x.unsqueeze(2))           # B,n,d 样本的每个向量乘上对应的xi： xi* embedding
                                                          #       tf.mul:按位置乘.广播 (B,n,d) * (B,n,1) ->(B,n,d) 
                                                          #       离散特征对应的xi是1.假设数值型已经归一化
        
        #embed=self.droplayer(embed)
        
        # 每个filed 向量22交互
        e_sum= torch.sum(embed,1)                         # B,d   每个样本。所有embedding对应维度元素相加，得到e_sum
        e_sum_square=torch.square(e_sum)                  # B,d   (e_sum)^2
        
        e_square=torch.square(embed)                      # B,n,d  平方后的
        e_square_sum=torch.sum(e_square,1)                # B,d    每个维度相加
        
        f =0.5*(e_sum_square-e_square_sum)                # B,d    n个embedding，每个维度元素22交互的结果（可作为新特征，拼接到后边）
    
        y_score2= torch.sum(f,1)                          # (B,)
        
        logits=self.weight[0]*y_score1+self.weight[1]*y_score2                          # (B,)   最终分数
        
        # TODO:loss加正则项（最后加）/dropout/grad-clip等. 看下train-loop
        
        return logits

In [450]:
# deepFM： 标准的。 上述k个作为特征统一拼到deep的
class deepFM(nn.Module):
    def __init__(self,n_field,n_features,embed_size,hiddens,dropout=0,batchnorm=True):
        super(deepFM, self).__init__()
        """
        标准DeepFM
        n_field: 原始特征数目
        n_features: 离散特征one-hot之后,和dense的总特征个数. 这里包含了一个缺失值特征向量，paddding成0
        deep每层：linear + (bn) + relu + (dropout).  输出hidden层。  最后按需单独linear到1
        """
        
        input_size=n_field*embed_size       # 输入deep的特征是所有原始特征的embedding拼接
        self.dropout=dropout
        self.batchnorm=batchnorm
        self.mlp=self.build_mlp(input_size,hiddens)                           #多层mlp.输出hidden  是一个ModuleList
        self.finallinear=nn.Linear(hiddens[-1],1,bias=True)                   #最后一层linear
        
        self.__init_weight__()                                              # 初始化权重。(可以按情况调用。现在用kaiming)
        
    def __init_weight__(self):              # 初始化权重
        for layer in self.mlp:
            if (layer.__class__.__name__=='Linear'):  # 每层初始化
                self.init_linear(layer)           
        self.init_linear(self.finallinear)
    
    # nn.linear  默认是U[-1/sqrt(in) ,1/sqrt(in)],但drml、deepFM用的xvar_normal
    def init_linear(self,layer):
#    nn.init.kaiming_normal_(layer.weight, mode='fan_in', nonlinearity='relu')  #sqrt(2/inn) 或者 sqrt(2/out)
#    nn.init.constant_(layer.bias, 0)
        #自定义xvar_normal_
        inn=layer.in_features
        out=layer.out_features
        std1=np.sqrt(2.0 / (inn + out))
        std2=np.sqrt(2.0 /out)   
        W=np.random.normal(0.0, std1, size=(out, inn)).astype(np.float32)
        b = np.random.normal(0.0, std2, size=out).astype(np.float32)
        layer.weight.data.copy_(torch.tensor(W))
        layer.bias.data.copy_(torch.tensor(b))

    def build_mlp(self,input_size,hiddens):
        """
        hiddens:[256,56,32]
        输出最后一层的hidden节点 （dropout+激活后的），可直接linear+sigmoid到deepscore. 也可以拼其他特征后再linear
        """        
        layers=nn.ModuleList()
        
        hiddens.insert(0,input_size)     #  [inputsize,256,56,32]
        num_layer=len(hiddens)-1         #  3层
        
        for i in range(0,len(hiddens)-1):
            
            # 线性层
            in_dim=hiddens[i]
            out_dim=hiddens[i+1]
            layer=nn.Linear(in_dim,out_dim,bias=True)
            layers.append(layer)
            
            # BN
            if self.batchnorm:
                layers.append(nn.BatchNorm1d(out_dim)) 
            
            # active + dropout
            layers.append(nn.ReLU())
            layers.append(nn.Dropout(self.dropout))
                
        return layers  # 拼成一个前后连接的网络。可以在forward里作为一个模块被整体调用
    
    
    # TODO:finish forward and train_loop
    def forward(self,f_p,f_x): # B,n.  n是每个样本的原始特征数目
        pass 
        
        
        

In [451]:
n_field=len(dis_col)                   # 原始离散特征数目
n_features=len(f_trans.feature_id_map) # 连续+离散特征的总数目 (离散特征one-hot+unique化后的。且算上最终的一个padding)
embed_size=8

In [452]:
hiddens=[256,56,32]
model=deepFM(n_field,n_features,embed_size,hiddens,dropout=0.5)

In [453]:
model

deepFM(
  (mlp): ModuleList(
    (0): Linear(in_features=208, out_features=256, bias=True)
    (1): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU()
    (3): Dropout(p=0.5, inplace=False)
    (4): Linear(in_features=256, out_features=56, bias=True)
    (5): BatchNorm1d(56, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (6): ReLU()
    (7): Dropout(p=0.5, inplace=False)
    (8): Linear(in_features=56, out_features=32, bias=True)
    (9): BatchNorm1d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (10): ReLU()
    (11): Dropout(p=0.5, inplace=False)
  )
  (finallinear): Linear(in_features=32, out_features=1, bias=True)
)

In [435]:
for i in model.mlp:
    #print(i)
    if(i.__class__.__name__=='Linear'):
        print(i.weight)
        print(i.bias)
        print(i.in_features)
        print(i.out_features)
        break

Parameter containing:
tensor([[-0.0325, -0.2011,  0.0048,  ..., -0.0487, -0.0874,  0.1735],
        [ 0.0861,  0.2162,  0.0436,  ...,  0.0543,  0.0334, -0.1347],
        [ 0.0563,  0.0118, -0.0538,  ..., -0.0876,  0.1231, -0.1035],
        ...,
        [-0.0705, -0.0031,  0.0527,  ...,  0.0603,  0.1637, -0.0366],
        [ 0.0041,  0.2787,  0.0464,  ...,  0.0917,  0.0307,  0.1608],
        [-0.1646,  0.1590, -0.0129,  ...,  0.0109, -0.0045,  0.0392]],
       requires_grad=True)
Parameter containing:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [438]:
model=FM(n_field,n_features,embed_size)
logits=model(f_p,f_v)
target=y
loss_func= nn.BCEWithLogitsLoss()    #  mean [yn⋅logσ(xn)+(1−yn)⋅log(1−σ(xn))]
loss=loss_func(logits,target.float())

In [439]:
target

tensor([0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 1])

In [440]:
pred_score

tensor([-4.1366e+03, -7.1312e+01, -1.3513e+03,  1.4476e+03, -1.9275e+02,
        -1.8003e+04,  1.7490e+03, -4.3147e+05,  6.5887e+03, -1.7615e+04,
         8.5446e+01,  1.1098e+02,  4.9213e+02, -1.3287e+03, -8.3064e+04,
         1.5444e+01, -2.3886e+04, -1.7416e+04,  1.5104e+03, -1.0096e+02,
         3.4893e+03, -1.3460e+04, -2.2060e+02,  6.8706e+02,  6.3637e+02,
        -1.3474e+05, -8.7573e+03, -9.9145e+00, -5.5055e+05, -1.4373e+04,
        -1.0077e+02, -4.6697e+02], dtype=torch.float64, grad_fn=<AddBackward0>)

In [442]:
loss

tensor(43944.4961, grad_fn=<BinaryCrossEntropyWithLogitsBackward>)

In [443]:
f.shape  # 可以作为新特征

torch.Size([32, 8])

In [444]:
model.feature_embed.weight

Parameter containing:
tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.6425, -0.1417, -0.3534,  ..., -0.5407, -0.8229,  0.0586],
        [ 0.7237,  0.7341,  0.7684,  ...,  0.0942,  0.3730, -0.0089],
        ...,
        [ 0.4576,  0.8214, -0.5743,  ...,  0.5860,  0.7545,  0.2372],
        [-0.7028, -0.5834, -0.5005,  ...,  0.6653, -0.6866,  0.6435],
        [ 0.2765, -0.4677,  0.0959,  ..., -0.4611, -0.6402,  0.5424]],
       requires_grad=True)

In [445]:
model.W.weight

Parameter containing:
tensor([[ 0.0000e+00],
        [-9.9967e-02],
        [ 5.4758e-02],
        [-5.4164e-02],
        [ 3.7269e-04],
        [-1.5212e-01],
        [-6.1737e-02],
        [ 1.4825e-01],
        [-3.0410e-02],
        [ 1.1927e-01],
        [ 6.0692e-02],
        [-8.3659e-02],
        [-1.6119e-01],
        [-9.4205e-02],
        [ 1.3356e-01],
        [ 4.1474e-02],
        [ 1.9476e-06],
        [-8.0247e-02],
        [-1.5026e-01],
        [-1.0389e-01],
        [-4.8330e-02],
        [ 3.2824e-02],
        [ 1.9687e-02],
        [-2.2626e-02],
        [-3.6300e-02],
        [-7.0286e-02],
        [-1.3579e-01],
        [ 1.1775e-01],
        [-2.3848e-02],
        [-6.4004e-02],
        [-7.0914e-02],
        [-5.7987e-02],
        [-5.2965e-02],
        [-8.5065e-03],
        [-7.1977e-02],
        [-8.9580e-02],
        [-3.1281e-02],
        [ 1.2001e-01],
        [-1.6674e-01],
        [-2.3623e-02],
        [-4.0428e-02],
        [ 7.3017e-02],
        [-6.

In [322]:
model.__class__.__name__

'FM'

### train_loop